version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  checker:
    build:
      context: .
      dockerfile: common/checker.Dockerfile
    volumes:
      - ./services/checker/src/:/app
    env_file:
      - .env

  discord:
    build:
      context: .
      dockerfile: common/discord.Dockerfile
    volumes:
      - ./services/discord/src/:/app
    env_file:
      - .env

  synchronizer:
    build:
      context: .
      dockerfile: common/synchronizer.Dockerfile
    volumes:
      - ./services/synchronizer/src/:/app
    env_file:
      - .env